### ISSUE TITLE
DialogService OpenAsync & Close in a second/nested Dialog causes reinitialization and state loss of first/parent Dialog

### ISSUE THREAD

**Issue by Matthewsre** [radzenhq/radzen-blazor#174] opened 2021-07-16 01:41 UTC
I have a form that opens a Dialog using this code:

```C#
        [Inject]
        public DialogService _dialogService { get; set; }

        ......

        [Parameter]
        public int? Width { get; set; }

        ......

        private DialogOptions _options;
        private dynamic _currentModal;

        ......

        public async Task OpenAsync()
        {
            if(Width != null)
            {
                _options = new DialogOptions {
                    Width = $"{Width}px"
                };
            }
            _currentModal = await _dialogService.OpenAsync(Title, ds => ChildContent, _options);
        }

        public Task CloseAsync()
        {
            _dialogService.Close(_currentModal);
            return Task.CompletedTask;
        }
```

![image](https://user-images.githubusercontent.com/2955659/125877981-1141d8e4-5034-4214-99a4-425e06d7452e.png)

I have that same code in a separate child Blazor component used as a confirmation:

![image](https://user-images.githubusercontent.com/2955659/125878049-2433b1b5-b77b-4aa3-aeeb-8cd531264e93.png)

The problem is when opening and closing the second Dialog, the first Dialog completely loses all state and re-initializes a new component.

If someone clicks cancel or closes the second Dialog the state of the first Dialog should be preserved.

**Comment by enchev** [comment] 2021-07-16 05:34
Hey @Matthewsre,

Dialogs are rendered in a container (RadzenDialog) in the MainLayout. Not sure if preserving state is possible at all, still if you find a way we will gladly test a pull request.

**Comment by Matthewsre** [comment] 2021-07-16 18:18
@enchev, I was able to get this working with one of the other methods:

```C#
        // State of first modal is NOT lost when opening second modal
        public async Task OpenAsync<T>(Dictionary<string, object> parameters = null) where T : ComponentBase
        {
            SetOptions();
            _currentModal = await _dialogService.OpenAsync<T>(Title, parameters, _options);
        }

        // State of first modal is lost when opening second modal
        public async Task OpenAsync()
        {
            SetOptions();
            _currentModal = await _dialogService.OpenAsync(Title, ds => ChildContent, _options);
        }
```

When using the OpenAsync<T> option that takes a dictionary of parameters this is working as expected, but the behavior of the second non-generic method is not. It seems like there is something specific that causes this behavior to be different for the second option and somehow links all of the dialogs opened with it the same. Is this keyed on the Type passed in? 

I noticed the type is always "object" when using the second option and the dictionary value passed in is null.

Would be great if these could both work the same since I would prefer to not use the Dictionary for specifying component parameters.

**Comment by gd738429** [comment] 2022-12-16 04:35
Hi @MoriLuca ~
Could you provide complete code for your question?
Cause I tried the solution as well as yours, I can show the nested Dialog in my project.
Maybe we can find out the different between yours and mine, since you've provided the complete code.

**Comment by ghhv** [comment] 2023-03-13 05:51
I found this because I have the same issue as @MoriLuca.. A button on an OpenSideAsync should open a dialog.confirm but doesn't. I'm doing this with Maui Blazor and it actually crashes the app - Android shows the app unresponsive. Now to see if I can use @Matthewsre solution to make it work..

Did you find a fix @MoriLuca ?

**Comment by Schullebernd** [comment] 2023-03-26 21:31
Same issue here. It's a strange thing because it seems to depend on the size of the screen. The problem occured when I wanted to test the app on an iPhone. When I open a second dialog (inside another one) the app crashes.
1st dialog size 700x512px
2nd dialog size 700x650px
On normal desktop screens sizes everything works perfect. But testing it on smaller screen sizes, where the dialog fills the screen width (due to the responsive mechanism) and the content of the dialogs need to be scrolled, the following Exceptions occures, when closing the second dialog:
```
[2023-03-26T21:04:35.346Z] Error: Microsoft.JSInterop.JSException: Cannot read properties of null (reading 'getBoundingClientRect')
TypeError: Cannot read properties of null (reading 'getBoundingClientRect')
    at Object.clientRect (https://.../_content/Radzen.Blazor/Radzen.Blazor.js:1408:19)
    at https://.../_framework/blazor.server.js:1:3506
    at new Promise (<anonymous>)
    at Ft.beginInvokeJSFromDotNet (.../_framework/blazor.server.js:1:3480)
    at Ft._invokeClientMethod (.../_framework/blazor.server.js:1:75066)
    at Ft._processIncomingData (.../_framework/blazor.server.js:1:72690)
    at Ft.connection.onreceive (.../_framework/blazor.server.js:1:67003)
    at i.onmessage (.../_framework/blazor.server.js:1:51316)
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
   at Radzen.Blazor.Rendering.DialogContainer.OnDragStart(DraggableEventArgs args)
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Radzen.Blazor.Rendering.Draggable.OnMouseDown(MouseEventArgs args)
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
```

Some additional info. On my dev machine (windows 11 with chrome browser) I can not get it to an exception, even if I simulate the smaller screen sizes with chrome.
Hosted on azure cloud with a linux appservice and testing it with a chrome browser on windows 11 or on an iPhone it's reproduceable. Just open chrome --> F12 --> set view to iPhone XR --> 100% and try to open and close the second dialog several times.

Anyone else can confirm this?

**Comment by ghhv** [comment] 2023-03-27 00:44
My quick fix was to close the dialogue completely and pass back a flag in the result which allowed the main screen to pop up the confirmation. A workaround..

**Comment by Schullebernd** [comment] 2023-03-27 10:08
Thanks @ghhv. I considered to try your solution but...
I looked a little bit into the details of the exception and then searched for the source code in Radzen, where the exception gets thrown. It's here:

_Radzen.Blazor/Rendering/DialogContainer.razor_
```
async Task OnDragStart(DraggableEventArgs args)
    {
        clientX = args.ClientX;
        clientY = args.ClientY;

        shouldRender = false;
        var rect = await JSRuntime.InvokeAsync<Rect>("Radzen.clientRect", dialog);
        height = $"height: {rect.Height}px;";
        width = $"width: {rect.Width}px;";

        shouldRender = true;
    }
```
It seems that the OnDragStart(...) method gets called when closing a dialog on a small screen.
Now, after I set the Draggable Option to false. Everything is working perfectly. 

I should have created a new/dedicated issue because it seems not to be the same problem like the original one in the post here...

**Comment by LlamaNL** [comment] 2023-03-27 10:49
I had a similar issue where the proceeding dialogs were reinitialized upon closing a higher dialog. I solved it by injecting a singleton service into OpenAsync<T> which held my object.

**Comment by enchev** [comment] 2024-07-24 07:22
Dragging is now made completely client-side to avoid unnecessary content rendering.

**Closed by enchev** 2024-07-24 07:22 UTC

**Comment by franklupo** [comment] 2024-10-04 10:45
OpenSideAsync nested not work, close previous Side dialog.

How can I solve the problem?

**Comment by vukasinpetrovic** [comment] 2025-03-07 10:51
@enchev @franklupo I just found this issue as I experienced the same behaviour for Side dialog. Nesting regular dialog works, but not for Side dialogs, where it closes the previous one.

Would it be possible to also enable nesting of side dialogs?
