### ISSUE TITLE
Latest Blazor Breaks Bootstrap Layouts

### ISSUE THREAD

**Issue by mysteryx93** [radzenhq/radzen-blazor#1635] opened 2024-08-05 01:46 UTC
After updating Radzen, I'm having issues with broken Bootstrap layouts. After investigating, it's due to this being defined by Radzen, which overrides `box-sizing: border-box`

```
*::before,
*::after {
  box-sizing: inherit;
}
```

Radzen version 5.0.6

 - OS: Garuda Linux
 - Browser: FireDragon 11.15

I don't know why that code was introduces but you should avoid breaking Bootstrap layouts.

When I look in the browser with inspect tools and disable this Radzen rule, then the row comes back to normal.

Here's a sample row that should display on a single line; but now splits into 2.
```
<div class="row">
    <div class="col-2">Email:</div>
    <div class="col-10"><input type="text" style="width: 100%" /></div>
</div>
```

I tried fixing it with this in my CSS but it's not working. Removing `Radzen.Blazor.js` is the only "fix" I found.
```
*::before, *::after {
  box-sizing: border-box !important;
}
```

The other working fix is reverting back to `Radzen 4.34.4`

**Comment by yordanov** [comment] 2024-08-05 06:48
Duplicate of https://github.com/radzenhq/radzen-blazor/issues/1632

**Closed by yordanov** 2024-08-05 06:48 UTC
