### ISSUE TITLE
Problematic aligning of context menu items

### ISSUE THREAD

**Issue by OndrejUzovic** [radzenhq/radzen-blazor#624] opened 2022-09-29 08:09 UTC
After version 4.0 the aligning if items is set to center which breaks the behavior from previous versions. And it also looks strange.

![image](https://user-images.githubusercontent.com/55758368/192975700-86646929-5463-470a-a1fc-50af7188a07d.png)

instead of

![image](https://user-images.githubusercontent.com/55758368/192975942-6deb9bad-da27-4038-ab1e-3ac39ae282b4.png)

The problem is the items in the context menu are explicitly aligned to the center.

![image](https://user-images.githubusercontent.com/55758368/192976682-662b0354-72b6-4eaf-a84a-772ddd39482b.png)

Would it be possible to align them to 'start' so that the previous behavior is preserved?

**Comment by yordanov** [comment] 2022-09-29 08:32
The issue is fixed with https://github.com/radzenhq/radzen-blazor/commit/5ea729d0d063d31036ec4458ee38dc407761c896. Used `align-items: stretch` so that items are stretched across the width of the menu.

**Closed by yordanov** 2022-09-29 08:32 UTC
