### ISSUE TITLE
please add Slider 

### ISSUE THREAD

**Issue by Andrey-2021** [radzenhq/radzen-blazor#646] opened 2022-10-15 17:28 UTC
Please add Slider!
see
https://getuikit.com/docs/slider
https://getuikit.com/docs/slideshow
with
Thumbnav
https://getuikit.com/docs/thumbnav

Thanks!

**Comment by yordanov** [comment] 2022-10-17 15:13
@Andrey-2021, closing this issue as a duplicate of #629. Pull requests are welcome too!

**Closed by yordanov** 2022-10-17 15:13 UTC
