### ISSUE TITLE
Exception: Cannot set properties of null (setting 'innerHTML')

### ISSUE THREAD

**Issue by OndrejUzovic** [radzenhq/radzen-blazor#728] opened 2022-11-30 23:46 UTC
Several times a day I am experiencing a sporadic exception in the HtmlEditor component.

Unfortunately I am not able to find exact steps how to reproduce it but here are two typical callstacks:

**The most often it originates from OnFocus**
```
Wed 30.11.22 18:57:27.147077 ??? Unhandled exception in circuit 'OTSPMlpJNtv12ydYnFDK8WUTJQCY7NKSRIOI7-49ipQ'.
Exception:
Microsoft.JSInterop.JSException: Cannot read properties of null (reading 'innerHTML')
TypeError: Cannot read properties of null (reading 'innerHTML')
    at Object.queryCommands (https://xxx.azurewebsites.net/_content/Radzen.Blazor/Radzen.Blazor.js:1233:17)
    at https://xxx.azurewebsites.net/_framework/blazor.server.js:1:3506
    at new Promise (<anonymous>)
    at Ft.beginInvokeJSFromDotNet (https://xxx.azurewebsites.net/_framework/blazor.server.js:1:3480)
    at Ft._invokeClientMethod (https://xxx.azurewebsites.net/_framework/blazor.server.js:1:75072)
    at Ft._processIncomingData (https://xxx.azurewebsites.net/_framework/blazor.server.js:1:72696)
    at Ft.connection.onreceive (https://xxx.azurewebsites.net/_framework/blazor.server.js:1:67009)
    at i.onmessage (https://xxx.azurewebsites.net/_framework/blazor.server.js:1:51322)
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
   at Radzen.Blazor.RadzenHtmlEditor.UpdateCommandState()
   at Radzen.Blazor.RadzenHtmlEditor.OnFocus()
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
```

**In several cases it also originates from OnAfterRenderAsync**
```
Wed 30.11.22 12:24:58.046369 ??? Unhandled exception in circuit '166RL_ckzfG0waAfLDrPKmiQeRSyehRY2BJUm9q1OE4'.
Exception:
Microsoft.JSInterop.JSException: Cannot set properties of null (setting 'innerHTML')
TypeError: Cannot set properties of null (setting 'innerHTML')
    at Object.innerHTML (https://xxx.azurewebsites.net/_content/Radzen.Blazor/Radzen.Blazor.js:1219:21)
    at https://xxx.azurewebsites.net/_framework/blazor.server.js:1:3506
    at new Promise (<anonymous>)
    at Ft.beginInvokeJSFromDotNet (https://xxx.azurewebsites.net/_framework/blazor.server.js:1:3480)
    at Ft._invokeClientMethod (https://xxx.azurewebsites.net/_framework/blazor.server.js:1:75072)
    at Ft._processIncomingData (https://xxx.azurewebsites.net/_framework/blazor.server.js:1:72696)
    at Ft.connection.onreceive (https://xxx.azurewebsites.net/_framework/blazor.server.js:1:67009)
    at i.onmessage (https://xxx.azurewebsites.net/_framework/blazor.server.js:1:51322)
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
   at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
   at Radzen.Blazor.RadzenHtmlEditor.OnAfterRenderAsync(Boolean firstRender)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
```

I am also receiving a feedback that users sometimes lose their data entered into the HtmlEditor. I suspect it could be caused by this error.

Please, do you have any idea what could cause this problem? Could anything be wrong on my site that I should check and fix?

**Comment by akorchev** [comment] 2022-12-12 15:39
We are not able to reproduce this exception. The code that seems to fail is this: https://github.com/radzenhq/radzen-blazor/blob/master/Radzen.Blazor/wwwroot/Radzen.Blazor.js#L1226 which is invoked here: https://github.com/radzenhq/radzen-blazor/blob/master/Radzen.Blazor/RadzenHtmlEditor.razor.cs#L189

It seems that ContentEditable is null for some reason. This shouldn't happen as it is a `@ref` of a html element: https://github.com/radzenhq/radzen-blazor/blob/master/Radzen.Blazor/RadzenHtmlEditor.razor#L52

**Comment by tecxx** [comment] 2023-02-01 07:49
Hello, same issue here, same error message as in Hardik's screenshot. Unfortunately i can't really trigger the issue on my local dev machine, but in the hosted app running on azure app services it happens more or less consistently. I'll try to create a minimal repro sample.

**Comment by tecxx** [comment] 2023-02-01 22:34
Here is a minimal reproduction sample: https://github.com/tecxx/BlazorRTESample

run it, F12 for debugger, randomly click the tree nodes on the left in rapid fashion. at some point the app will crash like this:

![image](https://user-images.githubusercontent.com/4305825/216178661-e9fbc8fa-7542-48d4-864d-1bc67bb2d331.png)


![image](https://user-images.githubusercontent.com/4305825/216179198-be94b2c9-0bd5-466b-a18e-29a8256d76c7.png)

sometimes it takes ages to make it crash, sometimes it crashes at second or third click. very strange....

**Comment by tecxx** [comment] 2023-02-06 12:47
tried to find a solution for this today, what i found is

1.  the exception is triggered here: 

https://github.com/radzenhq/radzen-blazor/blob/master/Radzen.Blazor/wwwroot/Radzen.Blazor.js#L1231
ref is null, so accessing ref.innerHTML fails.

2. ContentEditable in https://github.com/radzenhq/radzen-blazor/blob/master/Radzen.Blazor/RadzenHtmlEditor.razor.cs#L189 is never null, it is always a correct ElementReference. the issue must stem from somewhere else

3. i can only reproduce the issue when having a HTMLEditor inside a component, that is loaded as part of another component. in the screenshot below, the top right editor is part of the main component, which contains a RadzenDataList to display multiple "tasks" components, which contain the editor instances where the crash is happening.

![image](https://user-images.githubusercontent.com/4305825/216973805-74bc1e33-f273-430a-9261-8816adf62902.png)


so this looks like this is some kind of race condition caused by delayed loading or something along those lines (?). the html component initializes with a short delay, while in the meantime rapid clicking already caused a switch to a new instance of the component. a still running javascript call now tries to access ref.innerHTML of an already disposed component.
... just guess, though. 

4. null check workaround

```
window.Radzen.innerHTML = function (ref, value) {
        if (value != undefined) {
            if (ref == null) {
                test = "";  // unknown bug https://github.com/radzenhq/radzen-blazor/issues/728
            } else {
                ref.innerHTML = value;
            }
        } else {
            return ref.innerHTML;
        }
    }
```

adding a check for ref==null gets rid of the exception. it also seems that (with a very short delay) the html content is displayed correctly. i tried it with an azure hosted webapp, where, due to all the delays, i could reproduce the crash very consistently. it has fully disappeared, and i can not see any data loading issues as well. 



no guarantees though....

**Comment by akorchev** [comment] 2023-02-06 14:57
@tecxx feel free to open a pull request with the null check.

**Comment by akorchev** [comment] 2023-02-25 18:05
I am closing this issue as the suggested fix has been merged and released.

**Closed by akorchev** 2023-02-25 18:05 UTC
