### ISSUE TITLE
Animate Accordion

### ISSUE THREAD

**Issue by 3hxx** [radzenhq/radzen-blazor#1056] opened 2023-07-10 21:11 UTC
**Describe the solution you'd like**
Ideally there would be a toggleable animation on all panel which stretches the viewport  so it creates a smooth transition instead of just appearing

**Describe alternatives you've considered**
N/A

**Additional context**
When you open an Accordion the content just appears, whereas my solution would be to animate that event.

**Comment by yordanov** [comment] 2024-08-05 12:22
Duplicate of https://github.com/radzenhq/radzen-blazor/issues/269

**Closed by yordanov** 2024-08-05 12:22 UTC
