### ISSUE TITLE
After change the culture, the months in DatePicker will not be localized (Blazor WASM).

### ISSUE THREAD

**Issue by husam-ebish** [radzenhq/radzen-blazor#29] opened 2021-01-21 16:19 UTC
**Describe the bug:**
After change the culture, the months in DatePicker will not be localized without reload the page.
There were no problems during the culture change in version 2.18.3. 
In the version last version the component actually changes the date format according to the language, but the months are not translated until after the page is reloaded.

This problem appeared in version 2.18.4 and still exists until the current version "3.0.1"

**To Reproduce**
Video: https://drive.google.com/file/d/1lTVuYMal2D_vpPc7vCtcrogPcBaWShK3/view?usp=sharing

**Expected behavior:**
The months should be translated without reload the page (just like version 2.18.3)

**Screenshots**
Same video in "To Reproduce"

**Desktop:**
OS: Windows 10
Browser: Chrome
Version: 87.0.4280.141 (Official Build) (64-bit)

**Comment by akorchev** [comment] 2021-01-21 16:21
This issue does not follow the suggested template. Please update it or I will have to close it.

**Comment by akorchev** [comment] 2021-01-25 09:21
Closing it since no reproduction was provided.

**Closed by akorchev** 2021-01-25 09:21 UTC
