### ISSUE TITLE
Sidebar ignores initial expanded state unless Responsive=false

### ISSUE THREAD

**Issue by drullo** [radzenhq/radzen-blazor#716] opened 2022-11-21 16:38 UTC
**Describe the bug**
As per the examples in the documentation, I have a Sidebar that is bound to a boolean property.  However, unlike the examples, I've set the initial state of my property to false.  The Sidebar ignores this initial state if the **Responsive** property is in the default **true** state.

The **OnInitialized** code for [RadzenSidebar.razor.cs](https://github.com/radzenhq/radzen-blazor/blob/master/Radzen.Blazor/RadzenSidebar.razor.cs) only sets the **expanded** value to that of **Expanded** if **Responsive** is false.  Perhaps this it the cause of the bug?

**Expected behavior**
The expected behavior is for the component to adhere to the value of the property to which it is bound.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 107.0.5304.107

**Comment by drullo** [comment] 2022-11-21 16:47
Thank you @akorchev.  I have issues with this behavior as I think it's counter-intuitive and not what most developers would expect.  I would expect that the initial state would adhere to whatever I set, independent of the **Responsive** value - as the two properties are independent.  The component can still be Responsive, even if the initial state of the sidebar is collapsed.  This still seems like a logic flaw to me.

**Comment by akorchev** [comment] 2022-11-21 17:03
Without this check this happens (I am reloading the browser here).
![responsive](https://user-images.githubusercontent.com/454726/203115327-a9ae4ec6-0669-43af-9b5a-a0b3a23dfe18.gif)

The sidebar renders expanded from the server (this is the default value of Expanded), then it collapses because the media query kicks in. This leads to a visible flicker which is not needed. Not sure if this can be avoided otherwise but I am open to ideas.

**Comment by PaulSinnema** [comment] 2023-02-17 16:42
This behavior by design is not nice.

**Comment by PaulSinnema** [comment] 2023-02-17 16:50
I made a work arround:

 ```
   <RadzenHeader>
        <RadzenStack Orientation="Orientation.Horizontal" JustifyContent="JustifyContent.End" AlignItems="AlignItems.End" Gap="1rem">
            <RadzenSidebarToggle Click=@ToggleSideBar Class="rz-m-0" />
        </RadzenStack>
    </RadzenHeader>

    <RadzenSidebar @bind-Expanded=@SidebarExpanded @bind-Visible=@SidebarVisible>
        <RadzenPanelMenu>
            <RadzenPanelMenuItem Text="Home" Icon="home" />
            <RadzenPanelMenuItem Text="Users" Icon="account_box" />
        </RadzenPanelMenu>
    </RadzenSidebar>

        private bool SidebarExpanded { get; set; }
        private bool SidebarVisible { get; set; } = false;

        private void ToggleSideBar()
        {
            SidebarExpanded = !SidebarExpanded;
            SidebarVisible = true;
            StateHasChanged();
        }
```

**Comment by PaulSinnema** [comment] 2023-02-20 22:37
> Here is my solution
> 
> ```
> <RadzenSidebar @bind-Expanded="@sidebarExpanded" @bind-Responsive="responsive" >
> 
> ...
> ...
> 
> @code {
>     bool sidebarExpanded = false;
>     bool responsive = false;
>     protected override void OnAfterRender(bool firstRender)
>     {
>         if (firstRender)
>         {
>             responsive = true;
>         }
>         base.OnAfterRender(firstRender);
>     }
> }
> ```

Many road lead to Rome ;-)

**Comment by akorchev** [comment] 2023-03-06 07:03
Closing this issue as there isn't anything actionable for the time being.

**Closed by akorchev** 2023-03-06 07:03 UTC
